# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
# << macros

Name:       kde5-kwalletmanager
Summary:    KDE Wallet Manager is a tool to manage the passwords on your Plasma system.
Version:    5.0.0
Release:    1
Group:      System/Base
License:    GPLv2+
URL:        http://www.kde.org
Source0:    %{name}-%{version}.tar.xz
Source100:  kde5-kwalletmanager.yaml
Source101:  kde5-kwalletmanager-rpmlintrc
Requires:   kde5-filesystem
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(Qt5Xml)
BuildRequires:  pkgconfig(Qt5Network)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5Widgets)
BuildRequires:  pkgconfig(Qt5Concurrent)
BuildRequires:  pkgconfig(Qt5Test)
BuildRequires:  pkgconfig(Qt5PrintSupport)
BuildRequires:  kde5-rpm-macros
BuildRequires:  extra-cmake-modules
BuildRequires:  qt5-tools
BuildRequires:  kf5-kcoreaddons-devel
BuildRequires:  kf5-kdoctools-devel
BuildRequires:  kf5-kauth-devel
BuildRequires:  kf5-kwallet-devel
BuildRequires:  kf5-kservice-devel
BuildRequires:  kf5-kcmutils-devel
BuildRequires:  kf5-kdelibs4support-devel
BuildRequires:  kf5-ki18n-devel
BuildRequires:  kf5-kxmlgui-devel
BuildRequires:  kf5-kconfig-devel
BuildRequires:  kf5-kconfigwidgets-devel
BuildRequires:  kf5-kdbusaddons-devel


%description
KDE Wallet Manager is a tool to manage the passwords on your Plasma system.




%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
# << setup

%build
# >> build pre
%kde5_make
# << build pre



# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
%kde5_make_install
# << install pre

# >> install post
# << install post






%files
%defattr(-,root,root,-)
%doc COPYING COPYING.LIB
%{_kde5_bindir}/kwalletmanager
%{_kde5_sysconfdir}/dbus-1/system.d/org.kde.kcontrol.kcmkwallet.conf
%{_kde5_plugindir}/kcm_kwallet.so
%{_kde5_libexecdir}/kcm_kwallet_helper
%{_datadir}/applications/*
%{_datadir}/dbus-1/system-services/org.kde.kcontrol.kcmkwallet.service
%{_datadir}/doc/HTML/en/kwallet
%{_datadir}/icons/*
%{_kde5_datadir}/kwalletmanager5
%{_datadir}/kservices5/*
%{_datadir}/polkit-1/actions/org.kde.kcontrol.kcmkwallet.policy
# >> files
# << files


