# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       kwalletmanager

# >> macros
# << macros

Summary:    KDE Wallet Manager is a tool to manage the passwords on your Plasma system.
Version:    5.1.0
Release:    1
Group:      System/Base
License:    GPLv2+
URL:        http://www.kde.org
Source0:    %{name}-%{version}.tar.xz
Source100:  kwalletmanager.yaml
Source101:  kwalletmanager-rpmlintrc
Requires:   kf5-filesystem
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(Qt5Xml)
BuildRequires:  pkgconfig(Qt5Network)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5Widgets)
BuildRequires:  pkgconfig(Qt5Concurrent)
BuildRequires:  pkgconfig(Qt5Test)
BuildRequires:  pkgconfig(Qt5PrintSupport)
BuildRequires:  kf5-rpm-macros
BuildRequires:  extra-cmake-modules
BuildRequires:  qt5-tools
BuildRequires:  kcoreaddons-devel
BuildRequires:  kdoctools-devel
BuildRequires:  kauth-devel
BuildRequires:  kwallet-devel
BuildRequires:  kservice-devel
BuildRequires:  kcmutils-devel
BuildRequires:  kdelibs4support-devel
BuildRequires:  ki18n-devel
BuildRequires:  kxmlgui-devel
BuildRequires:  kconfig-devel
BuildRequires:  kconfigwidgets-devel
BuildRequires:  kdbusaddons-devel

%description
KDE Wallet Manager is a tool to manage the passwords on your Plasma system.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
%kf5_make
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
%kf5_make_install
# << install pre

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%doc COPYING COPYING.LIB
%{_kf5_bindir}/kwalletmanager5
%{_kf5_sysconfdir}/dbus-1/system.d/org.kde.kcontrol.kcmkwallet.conf
%{_kf5_plugindir}/*
%{_kf5_libdir}/*
%{_datadir}/applications/*
%{_datadir}/dbus-1/system-services/org.kde.kcontrol.kcmkwallet.service
%{_kf5_htmldir}/en/kwallet
%{_kf5_iconsdir}/*
%{_kf5_sharedir}/kxmlgui5/*
%{_kf5_sharedir}/kwalletmanager5
%{_kf5_servicesdir}/*
%{_datadir}/polkit-1/actions/org.kde.kcontrol.kcmkwallet.policy
# >> files
# << files
